/*
 * Test class to validate each public method from OpportunityService
 * */
@IsTest
public class OpportunityServiceTest {

    
    @IsTest
    public static void assignNewRecordsAvailableTeamMember() {
        //Unit test to assignNewRecords
    }
    
    @IsTest
    public static void assignNewRecordsUnavailableTeamMember() {
        //Unit test to assignNewRecords
    }
    
    @IsTest
    public static void closedOpportunitiesWithOpenOpportunities() {
        //unit test to closedOpportunities
    }
    
    @IsTest
    public static void closedOpportunitiesWithoutOpenOpportunities() {
        //unit test to closedOpportunities
    }
}